db: gin_blogs:tmp_pwd@tcp(127.0.0.1:3306)/gin_blogs?charset=utf8&parseTime=true
redis: "localhost:6379"
fb_oauth: 
  client_id: "d065a371-67c4-460b-adcd-fecd019a0ec8"
  client_secret: "a50c7534-7a07-4b7d-81e3-30324d45d00f"
